import pandas as pd
import matplotlib.pyplot as plt

def plot_training_results(log_file):
    """
    Reads the CSV log file (generated by Monitor) and plots episode rewards.
    """
    try:
        df = pd.read_csv(log_file, skiprows=1)
    except Exception as e:
        print(f"Error reading log file: {e}")
        return
    if 'r' not in df.columns:
        print("Log file does not contain reward column 'r'")
        return

    plt.figure(figsize=(10, 6))
    plt.plot(df['r'], label="Episode Reward")
    plt.xlabel("Episode")
    plt.ylabel("Reward")
    plt.title("Training Reward per Episode")
    plt.legend()
    plt.show()
